name: riiaa20
channels:
   - defaults
   - anaconda
   - conda-forge
dependencies:
   - python>=3.7
   - pip
   - numpy
   - scipy
   - pandas
   - matplotlib
   - seaborn
   - jupyter
   - ipykernel
   - tqdm
   - scikit-learn
   - folium
   - geopy
   - pip:
     - statsmodels
